version: '3.8'

services:
  traefik:  
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/traefik-configuration.yml"
      - "--entrypoints.web.address=:80"
      -  "--entrypoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-configuration.yml:/etc/traefik/traefik-configuration.yml"
    networks:
      - financial-app-net

  rabbitmq: 
    image: rabbitmq:4-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
    networks:
      - financial-app-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  financial-db:
    image: postgres:latest
    container_name: financial-db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${FINANCIAL_DB_PASSWORD}
      POSTGRES_DB: FinancialDb
    volumes:
      - financial_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - financial-app-net

  notification-db:
    image: postgres:latest
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      POSTGRES_DB: NotificationDB
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - financial-app-net

  authorization-db:
    image: postgres:latest
    container_name: authorization-db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${AUTHORIZATION_DB_PASSWORD}
      POSTGRES_DB: AuthorizationDB
    volumes:
      - authorization_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - financial-app-net

  authorization-service:
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile
    container_name: authorization-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5233
    volumes:
      - /app/logs
    networks:
      - financial-app-net

  financial-app:
    build:
      context: .
      dockerfile: FinancialApp/Dockerfile
    container_name: financial-app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5113
    volumes:
      - /app/logs
    networks:
      - financial-app-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notification-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5102
    volumes:
      - /app/logs
    networks:
      - financial-app-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  financial-app-net:
    driver: bridge

volumes:
  financial_db_data:
  notification_db_data:
  authorization_db_data:  