/**
 * FinancialApp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TimePeriod = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const TimePeriod = {
    NUMBER_1: 1 as TimePeriod,
    NUMBER_2: 2 as TimePeriod,
    NUMBER_3: 3 as TimePeriod,
    NUMBER_4: 4 as TimePeriod,
    NUMBER_5: 5 as TimePeriod,
    NUMBER_6: 6 as TimePeriod,
    NUMBER_7: 7 as TimePeriod,
    NUMBER_8: 8 as TimePeriod,
    NUMBER_9: 9 as TimePeriod
};

